name: Annoncement
main: fr.niasio.annoncement.AnnoncementV3
version: 3.0
author: Niasio

commands:
 annonceon:
  description: Making an announcement with nick.
  permission: annonce.on
 annonceoff:
  description: Making an announcement without nick.
  permission: annonce.off
 annoncereload:
  description: Reload plugin.
  permission: annonce.reload